package wsLearning;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller    // This means that this class is a Controller
@RequestMapping(path = "/employee") // This means URL's start with /employee (after Application path)
public class EmployeeInfoController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private EmployeeInfoRepository employeeInfoRepository;

    @PostMapping(value = "/add")
    public String addNewEmployee(@RequestBody EmployeeInfo employeeInfo) {

        employeeInfoRepository.save(employeeInfo);

        return "Add new employee success!";
    }

    @GetMapping(value = "/getAll")
    public @ResponseBody
    Iterable<EmployeeInfo> getAllEmployee() {
        // This returns a JSON or XML with the users
        return employeeInfoRepository.findAll();
    }


}
