package wsLearning;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller    // This means that this class is a Controller
@RequestMapping(path = "/employee") // This means URL's start with /employee (after Application path)
public class MainController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private EmployeeInfoRepository employeeInfoRepository;

    @PostMapping(path = "/add")
    public @ResponseBody
    String addNewEmployee(@RequestParam int id, @RequestParam String name, @RequestParam int age, @RequestParam String email) {

        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        EmployeeInfo ei = new EmployeeInfo();
        ei.setId(id);
        ei.setName(name);
        ei.setAge(age);
        ei.setEmail(email);
        employeeInfoRepository.save(ei);
        return "Saved";
    }

    @GetMapping(path = "/getAll")
    public @ResponseBody
    Iterable<EmployeeInfo> getAllEmployee() {
        // This returns a JSON or XML with the users
        return employeeInfoRepository.findAll();
    }


}
